package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/kevingates/exchange/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Currency)
// DB Table: Plural (currencies)
// Resource: Plural (Currencies)
// Path: Plural (/currencies)
// View Template Folder: Plural (/templates/currencies/)

// CurrenciesResource is the resource for the Currency model
type CurrenciesResource struct {
	buffalo.Resource
}

// List gets all Currencies. This function is mapped to the path
// GET /currencies
func (v CurrenciesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	currencies := &models.Currencies{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Currencies from the DB
	if err := q.All(currencies); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, currencies))
}

// Show gets the data for one Currency. This function is mapped to
// the path GET /currencies/{currency_id}
func (v CurrenciesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Currency
	currency := &models.Currency{}

	// To find the Currency the parameter currency_id is used.
	if err := tx.Find(currency, c.Param("currency_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, currency))
}

// New renders the form for creating a new Currency.
// This function is mapped to the path GET /currencies/new
func (v CurrenciesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Currency{}))
}

// Create adds a Currency to the DB. This function is mapped to the
// path POST /currencies
func (v CurrenciesResource) Create(c buffalo.Context) error {
	// Allocate an empty Currency
	currency := &models.Currency{}

	// Bind currency to the html form elements
	if err := c.Bind(currency); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(currency)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, currency))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Currency was created successfully")

	// and redirect to the currencies index page
	return c.Render(201, r.Auto(c, currency))
}

// Edit renders a edit form for a Currency. This function is
// mapped to the path GET /currencies/{currency_id}/edit
func (v CurrenciesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Currency
	currency := &models.Currency{}

	if err := tx.Find(currency, c.Param("currency_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, currency))
}

// Update changes a Currency in the DB. This function is mapped to
// the path PUT /currencies/{currency_id}
func (v CurrenciesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Currency
	currency := &models.Currency{}

	if err := tx.Find(currency, c.Param("currency_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Currency to the html form elements
	if err := c.Bind(currency); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(currency)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, currency))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Currency was updated successfully")

	// and redirect to the currencies index page
	return c.Render(200, r.Auto(c, currency))
}

// Destroy deletes a Currency from the DB. This function is mapped
// to the path DELETE /currencies/{currency_id}
func (v CurrenciesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Currency
	currency := &models.Currency{}

	// To find the Currency the parameter currency_id is used.
	if err := tx.Find(currency, c.Param("currency_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(currency); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Currency was destroyed successfully")

	// Redirect to the currencies index page
	return c.Render(200, r.Auto(c, currency))
}
